### ISSUE TITLE
Consider using RegExp syntax for Vue.config.ignoredElements

### ISSUE THREAD

**Issue by leopiccionia** [PaulHalliday/Ionic-4-Vue.js#1]
Firstly, nice tutorial!

From Vue 2.5+, [Vue.config.ignoredElements](https://vuejs.org/v2/api/#ignoredElements) accepts `RegExp` inside array parameter (the docs example, actually, uses Ionic components!).

So, I suggest upgrading Vue and using the following syntax, that IMHO helps to demystify Ionic usage in Vue:
```javascript
Vue.config.ignoredElements = [/^ion-/]
```

**Comment by PaulHalliday** [comment]
Good point! I've changed this as requested. :)
